services:
  llm_api:
    build:
      dockerfile: ./Dockerfile
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 200s
      timeout: 200s
      retries: 5
    ports:
      - ${API_PORT}:8000
    networks:
      - llm_api_net

networks:
  llm_api_net:
